const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates an attendance PDF report for a single session.
 * @param {Object} session - { courseCode, instructorEmail, venueName, venue: { name }, date, time, expectedStudents }
 * @param {Array} records - [{ name, studentName, regNumber, studentId, checkInTime, checkOutTime }]
 * @param {Number} riskThreshold - attendance % below which to flag
 * @returns {Promise<string>} path to the generated PDF
 */
function generateAttendancePDF(session, records, riskThreshold = 75) {
  const outputPath = path.join(
    __dirname,
    '..',
    'reports',
    `${session.courseCode}_${session.date}_${Date.now()}.pdf`
  );

  const doc = new PDFDocument({ margin: 50 });
  const stream = fs.createWriteStream(outputPath);
  doc.pipe(stream);

  // Header
  doc.fontSize(16).font('Helvetica-Bold').text('MZUZU UNIVERSITY', { align: 'center' });
  doc.fontSize(12).font('Helvetica').text('EasyAttend - Attendance Report', { align: 'center' });
  doc.moveDown(1);

  // Session details
  doc.fontSize(10);
  doc.font('Helvetica-Bold').text('Course: ', { continued: true })
     .font('Helvetica').text(`${session.courseCode}`);
  doc.font('Helvetica-Bold').text('Instructor: ', { continued: true })
     .font('Helvetica').text(session.instructorEmail || 'N/A');
  doc.font('Helvetica-Bold').text('Venue: ', { continued: true })
     .font('Helvetica').text(session.venueName || session.venue?.name || 'N/A');
  doc.font('Helvetica-Bold').text('Date: ', { continued: true })
     .font('Helvetica').text(session.date || 'N/A');
  doc.font('Helvetica-Bold').text('Time: ', { continued: true })
     .font('Helvetica').text(session.time || `${session.startTime || ''} - ${session.endTime || ''}`.trim() || 'N/A');
  doc.font('Helvetica-Bold').text('Total Present: ', { continued: true })
     .font('Helvetica').text(`${records.length}`);

  if (session.expectedStudents) {
    const rate = ((records.length / session.expectedStudents) * 100).toFixed(1);
    doc.font('Helvetica-Bold').text('Attendance Rate: ', { continued: true })
       .font('Helvetica').text(`${rate}% of expected class size`);

    if (parseFloat(rate) < riskThreshold) {
      doc.fillColor('red')
         .font('Helvetica-Bold')
         .text(`Below ${riskThreshold}% threshold - flagged for review`);
      doc.fillColor('black');
    }
  }

  doc.moveDown(1);

  // Table header
  const startX = 50;
  let y = doc.y;
  const colWidths = [30, 150, 100, 90, 90];
  const headers = ['#', 'Name', 'Reg Number', 'Check-In', 'Check-Out'];

  doc.font('Helvetica-Bold').fontSize(9);
  let x = startX;
  headers.forEach((h, i) => {
    doc.text(h, x, y, { width: colWidths[i] });
    x += colWidths[i];
  });
  doc.moveTo(startX, y + 15).lineTo(550, y + 15).stroke();

  // Table rows
  doc.font('Helvetica').fontSize(9);
  y += 22;

  records.forEach((r, idx) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }
    x = startX;
    const row = [
      String(idx + 1),
      r.name || r.studentName || '-',
      r.regNumber || r.studentId || '-',
      r.checkInTime || '-',
      r.checkOutTime || '-',
    ];
    row.forEach((val, i) => {
      doc.text(val, x, y, { width: colWidths[i] });
      x += colWidths[i];
    });
    y += 20;
  });

  // Footer
  doc.fontSize(8).fillColor('gray')
     .text(`Generated by EasyAttend on ${new Date().toLocaleString()}`, 50, 770);

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
}

module.exports = { generateAttendancePDF };
