const { db } = require('./services/firebaseAdmin');

async function clearCollection(name) {
  const snapshot = await db.collection(name).get();
  const docs = snapshot.docs;
  for (let i = 0; i < docs.length; i += 400) {
    const batch = db.batch();
    docs.slice(i, i + 400).forEach((doc) => batch.delete(doc.ref));
    await batch.commit();
  }
  console.log(`Cleared ${docs.length} old docs from '${name}'`);
}

const students = [
  { name: "Madalitso Kalua", regNumber: "BTRS1506", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Patrick Chunga", regNumber: "BTRS1508", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Grace Zimba", regNumber: "BTRS1511", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Ethel Kamanga", regNumber: "BTRS1512", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Chikondi Chiumia", regNumber: "BTRS1513", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Pemphero Msusa", regNumber: "BTRS1515", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Kondwani Mhango", regNumber: "BTRS1517", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Sarah Kaunda", regNumber: "BTRS1519", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Patrick Mtonga", regNumber: "BTRS1520", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Linda Kaweche", regNumber: "BTRS1521", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Lazarus Chisale", regNumber: "BTRS1525", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Pemphero Tembo", regNumber: "BTRS1527", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Tiwonge Mlozi", regNumber: "BTRS1530", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Florence Mwale", regNumber: "BTRS1532", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Wongani Sangala", regNumber: "BTRS1534", courseCode: "BTRS 1206", classLevel: 1, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Takondwa Msusa", regNumber: "EDUF1522", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Chikondi Chiwaya", regNumber: "EDUF1525", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Blessings Ngwira", regNumber: "EDUF1529", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Tadala Manda", regNumber: "EDUF1531", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Owen Banda", regNumber: "EDUF1534", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Bright Tembo", regNumber: "EDUF1536", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Annie Kanyenda", regNumber: "EDUF1537", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Takondwa Mlozi", regNumber: "EDUF1539", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Daniel Nkhoma", regNumber: "EDUF1543", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Brenda Mlozi", regNumber: "EDUF1544", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Limbani Mbewe", regNumber: "EDUF1546", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Wezi Tembo", regNumber: "EDUF1550", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Patricia Nkata", regNumber: "EDUF1551", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Steven Mwale", regNumber: "EDUF1553", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Davie Mwale", regNumber: "EDUF1557", courseCode: "EDUF 1201", classLevel: 1, programName: "Bachelor of Education (Arts)" },
  { name: "Mphatso Kachepa", regNumber: "GEOG1547", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Yamikani Kambwiri", regNumber: "GEOG1549", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Lusungu Mtonga", regNumber: "GEOG1551", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Takondwa Chipeta", regNumber: "GEOG1555", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Susan Mhango", regNumber: "GEOG1558", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Innocent Kapito", regNumber: "GEOG1561", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Sarah Banda", regNumber: "GEOG1564", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Ulemu Sangala", regNumber: "GEOG1565", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Gift Msusa", regNumber: "GEOG1569", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Madalitso Nkhoma", regNumber: "GEOG1570", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Chimwemwe Phiri", regNumber: "GEOG1573", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Lazarus Nkata", regNumber: "GEOG1575", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Agnes Kanyenda", regNumber: "GEOG1577", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Madalitso Kamanga", regNumber: "GEOG1578", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Edna Chiwaya", regNumber: "GEOG1581", courseCode: "GEOG 1201", classLevel: 1, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Chimwemwe Kamanga", regNumber: "FREN1538", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Steven Kasambala", regNumber: "FREN1541", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Brenda Mtonga", regNumber: "FREN1542", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Khumbo Nyirenda", regNumber: "FREN1546", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Khumbo Kasambala", regNumber: "FREN1550", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Veronica Mwale", regNumber: "FREN1551", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Grace Mtonga", regNumber: "FREN1552", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Innocent Tembo", regNumber: "FREN1555", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Owen Lungu", regNumber: "FREN1557", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Samuel Zimba", regNumber: "FREN1560", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Agnes Kachepa", regNumber: "FREN1563", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Annie Mwale", regNumber: "FREN1566", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Tamanda Khonje", regNumber: "FREN1567", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Mercy Banda", regNumber: "FREN1571", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Trust Gondwe", regNumber: "FREN1574", courseCode: "FREN 1201", classLevel: 1, programName: "Bachelor of Education (Languages)" },
  { name: "Tionge Tembo", regNumber: "BTRS1536", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Ulemu Ngwira", regNumber: "BTRS1538", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Tionge Ngwira", regNumber: "BTRS1539", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Pemphero Mtonga", regNumber: "BTRS1542", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Steria Kanyenda", regNumber: "BTRS1546", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Chikondi Mwale", regNumber: "BTRS1550", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Mphatso Chisale", regNumber: "BTRS1552", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Madalitso Nkata", regNumber: "BTRS1554", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Catherine Kapito", regNumber: "BTRS1558", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Joyce Zimba", regNumber: "BTRS1559", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Joyce Kapito", regNumber: "BTRS1561", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Dalitso Lungu", regNumber: "BTRS1563", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Lazarus Chibwana", regNumber: "BTRS1566", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Pemphero Soko", regNumber: "BTRS1568", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Tarisai Mhango", regNumber: "BTRS1569", courseCode: "BTRS 2402", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Tarisai Mtonga", regNumber: "GEOG1585", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Agnes Chirwa", regNumber: "GEOG1586", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Davie Soko", regNumber: "GEOG1587", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Yankho Chiwaya", regNumber: "GEOG1589", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Kondwani Kamanga", regNumber: "GEOG1591", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Agnes Chipeta", regNumber: "GEOG1593", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Veronica Mtonga", regNumber: "GEOG1596", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Florence Banda", regNumber: "GEOG1597", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Patricia Soko", regNumber: "GEOG1600", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Ulemu Chunga", regNumber: "GEOG1602", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Sarah Nkata", regNumber: "GEOG1606", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Joseph Kalua", regNumber: "GEOG1608", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Tionge Nkhoma", regNumber: "GEOG1609", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Tapiwa Banda", regNumber: "GEOG1610", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Edna Soko", regNumber: "GEOG1614", courseCode: "GEOG 2404", classLevel: 2, programName: "Bachelor of Arts (Development Studies)" },
  { name: "Joseph Kambwiri", regNumber: "BTRS1573", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Ruth Chiumia", regNumber: "BTRS1574", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Florence Mtonga", regNumber: "BTRS1576", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Catherine Mtonga", regNumber: "BTRS1578", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Tapiwa Ngwira", regNumber: "BTRS1581", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Chisomo Kachepa", regNumber: "BTRS1585", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Davie Kanyenda", regNumber: "BTRS1587", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Patrick Banda", regNumber: "BTRS1591", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Daniel Kapito", regNumber: "BTRS1592", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Memory Khonje", regNumber: "BTRS1595", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Tarisai Tembo", regNumber: "BTRS1597", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Beatrice Mtonga", regNumber: "BTRS1599", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Ireen Chimombo", regNumber: "BTRS1603", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Yamikani Phiri", regNumber: "BTRS1605", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Sarah Phiri", regNumber: "BTRS1606", courseCode: "BTRS 2401", classLevel: 2, programName: "Bachelor of Arts (Theology and Religious Studies)" },
  { name: "Brenda Soko", regNumber: "FREN1578", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Patrick Phiri", regNumber: "FREN1580", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Dalitso Kapito", regNumber: "FREN1582", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Tamanda Kaweche", regNumber: "FREN1584", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Mphatso Gondwe", regNumber: "FREN1588", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Andrew Kapito", regNumber: "FREN1590", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Steria Chimombo", regNumber: "FREN1592", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Susan Kaweche", regNumber: "FREN1595", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Khama Soko", regNumber: "FREN1597", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Joseph Nyirenda", regNumber: "FREN1598", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Towera Ngwira", regNumber: "FREN1600", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Grace Chiumia", regNumber: "FREN1602", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Vitumbiko Sangala", regNumber: "FREN1604", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Wezi Kamanga", regNumber: "FREN1608", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Nelson Kalua", regNumber: "FREN1612", courseCode: "FREN 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Andrew Chimombo", regNumber: "EDUF1558", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Grace Chisale", regNumber: "EDUF1560", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Agnes Tembo", regNumber: "EDUF1563", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Hope Mlozi", regNumber: "EDUF1566", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Khama Kalua", regNumber: "EDUF1569", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Faith Chiwaya", regNumber: "EDUF1573", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Khama Phiri", regNumber: "EDUF1575", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Lusungu Kambwiri", regNumber: "EDUF1576", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Tamanda Kanyenda", regNumber: "EDUF1577", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Loveness Mlozi", regNumber: "EDUF1578", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Daniel Banda", regNumber: "EDUF1582", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Fatsani Sangala", regNumber: "EDUF1583", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Samuel Chirwa", regNumber: "EDUF1586", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Zione Gondwe", regNumber: "EDUF1588", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Chisomo Munthali", regNumber: "EDUF1589", courseCode: "EDUF 3603", classLevel: 3, programName: "Bachelor of Education (Arts)" },
  { name: "Kondwani Manda", regNumber: "ENGL1545", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Ruth Banda", regNumber: "ENGL1547", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Trust Lungu", regNumber: "ENGL1550", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Frank Chiumia", regNumber: "ENGL1553", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Memory Kamanga", regNumber: "ENGL1554", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Goodson Gondwe", regNumber: "ENGL1557", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Towera Mvula", regNumber: "ENGL1559", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Limbani Sangala", regNumber: "ENGL1562", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Enock Zimba", regNumber: "ENGL1563", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Owen Soko", regNumber: "ENGL1565", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Chimwemwe Mtonga", regNumber: "ENGL1568", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Catherine Nkhoma", regNumber: "ENGL1572", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Fatsani Kaunda", regNumber: "ENGL1574", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Memory Manda", regNumber: "ENGL1577", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
  { name: "Hope Chisale", regNumber: "ENGL1580", courseCode: "ENGL 3601", classLevel: 3, programName: "Bachelor of Education (Languages)" },
];

async function seed() {
  await clearCollection('students');

  let added = 0;
  for (const student of students) {
    await db.collection('students').add({
      ...student,
      createdAt: new Date().toISOString(),
    });
    added++;
  }

  console.log(`✅ Added ${added} students (15 per course across 10 courses).`);
}

seed();